// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth_service.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignUpRequest struct {
	FullName             string   `protobuf:"bytes,1,opt,name=FullName,proto3" json:"FullName,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	PhoneNum             string   `protobuf:"bytes,4,opt,name=PhoneNum,proto3" json:"PhoneNum,omitempty"`
	BirthDate            string   `protobuf:"bytes,5,opt,name=BirthDate,proto3" json:"BirthDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRequest) Reset()         { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()    {}
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f39bb026ca10b68, []int{0}
}

func (m *SignUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRequest.Unmarshal(m, b)
}
func (m *SignUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRequest.Marshal(b, m, deterministic)
}
func (m *SignUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRequest.Merge(m, src)
}
func (m *SignUpRequest) XXX_Size() int {
	return xxx_messageInfo_SignUpRequest.Size(m)
}
func (m *SignUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRequest proto.InternalMessageInfo

func (m *SignUpRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *SignUpRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignUpRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SignUpRequest) GetPhoneNum() string {
	if m != nil {
		return m.PhoneNum
	}
	return ""
}

func (m *SignUpRequest) GetBirthDate() string {
	if m != nil {
		return m.BirthDate
	}
	return ""
}

type SignUpResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpResponse) Reset()         { *m = SignUpResponse{} }
func (m *SignUpResponse) String() string { return proto.CompactTextString(m) }
func (*SignUpResponse) ProtoMessage()    {}
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f39bb026ca10b68, []int{1}
}

func (m *SignUpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpResponse.Unmarshal(m, b)
}
func (m *SignUpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpResponse.Marshal(b, m, deterministic)
}
func (m *SignUpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpResponse.Merge(m, src)
}
func (m *SignUpResponse) XXX_Size() int {
	return xxx_messageInfo_SignUpResponse.Size(m)
}
func (m *SignUpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpResponse proto.InternalMessageInfo

func (m *SignUpResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SignUpResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type SignInRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInRequest) Reset()         { *m = SignInRequest{} }
func (m *SignInRequest) String() string { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()    {}
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f39bb026ca10b68, []int{2}
}

func (m *SignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRequest.Unmarshal(m, b)
}
func (m *SignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRequest.Marshal(b, m, deterministic)
}
func (m *SignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRequest.Merge(m, src)
}
func (m *SignInRequest) XXX_Size() int {
	return xxx_messageInfo_SignInRequest.Size(m)
}
func (m *SignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRequest proto.InternalMessageInfo

func (m *SignInRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignInRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignInResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInResponse) Reset()         { *m = SignInResponse{} }
func (m *SignInResponse) String() string { return proto.CompactTextString(m) }
func (*SignInResponse) ProtoMessage()    {}
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f39bb026ca10b68, []int{3}
}

func (m *SignInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInResponse.Unmarshal(m, b)
}
func (m *SignInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInResponse.Marshal(b, m, deterministic)
}
func (m *SignInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInResponse.Merge(m, src)
}
func (m *SignInResponse) XXX_Size() int {
	return xxx_messageInfo_SignInResponse.Size(m)
}
func (m *SignInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignInResponse proto.InternalMessageInfo

func (m *SignInResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SignInResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *SignInResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ValidateRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateRequest) Reset()         { *m = ValidateRequest{} }
func (m *ValidateRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateRequest) ProtoMessage()    {}
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f39bb026ca10b68, []int{4}
}

func (m *ValidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateRequest.Unmarshal(m, b)
}
func (m *ValidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateRequest.Marshal(b, m, deterministic)
}
func (m *ValidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateRequest.Merge(m, src)
}
func (m *ValidateRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateRequest.Size(m)
}
func (m *ValidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateRequest proto.InternalMessageInfo

func (m *ValidateRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ValidateResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	UserID               int64    `protobuf:"varint,3,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateResponse) Reset()         { *m = ValidateResponse{} }
func (m *ValidateResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateResponse) ProtoMessage()    {}
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f39bb026ca10b68, []int{5}
}

func (m *ValidateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateResponse.Unmarshal(m, b)
}
func (m *ValidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateResponse.Marshal(b, m, deterministic)
}
func (m *ValidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateResponse.Merge(m, src)
}
func (m *ValidateResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateResponse.Size(m)
}
func (m *ValidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateResponse proto.InternalMessageInfo

func (m *ValidateResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ValidateResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ValidateResponse) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func init() {
	proto.RegisterType((*SignUpRequest)(nil), "protobuf.SignUpRequest")
	proto.RegisterType((*SignUpResponse)(nil), "protobuf.SignUpResponse")
	proto.RegisterType((*SignInRequest)(nil), "protobuf.SignInRequest")
	proto.RegisterType((*SignInResponse)(nil), "protobuf.SignInResponse")
	proto.RegisterType((*ValidateRequest)(nil), "protobuf.ValidateRequest")
	proto.RegisterType((*ValidateResponse)(nil), "protobuf.ValidateResponse")
}

func init() {
	proto.RegisterFile("auth_service.proto", fileDescriptor_0f39bb026ca10b68)
}

var fileDescriptor_0f39bb026ca10b68 = []byte{
	// 342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x9b, 0xd6, 0x84, 0xf6, 0x8a, 0x3f, 0x0c, 0x52, 0x63, 0x70, 0x21, 0xb3, 0xd1, 0x55,
	0x05, 0x5d, 0x2b, 0xb4, 0x54, 0xa1, 0x9b, 0x22, 0x69, 0x2b, 0xe2, 0x46, 0xa6, 0x76, 0x34, 0xc1,
	0x34, 0x13, 0xe7, 0x47, 0x1f, 0xc5, 0xb7, 0xf2, 0x99, 0x24, 0x33, 0x99, 0xa4, 0x8d, 0xba, 0xe9,
	0x2a, 0x9c, 0x9c, 0x7b, 0x86, 0xef, 0x1e, 0x2e, 0x20, 0xa2, 0x64, 0xf4, 0x24, 0x28, 0xff, 0x88,
	0x9f, 0x69, 0x2f, 0xe3, 0x4c, 0x32, 0xd4, 0xd6, 0x9f, 0xb9, 0x7a, 0xc1, 0x5f, 0x0e, 0xec, 0x4c,
	0xe2, 0xd7, 0x74, 0x96, 0x85, 0xf4, 0x5d, 0x51, 0x21, 0x51, 0x00, 0xed, 0x5b, 0x95, 0x24, 0x63,
	0xb2, 0xa4, 0xbe, 0x73, 0xe2, 0x9c, 0x75, 0xc2, 0x52, 0xa3, 0x03, 0x70, 0x6f, 0x96, 0x24, 0x4e,
	0xfc, 0xa6, 0x36, 0x8c, 0xc8, 0x13, 0x77, 0x44, 0x88, 0x4f, 0xc6, 0x17, 0x7e, 0xcb, 0x24, 0xac,
	0xd6, 0x5e, 0xc4, 0x52, 0x3a, 0x56, 0x4b, 0x7f, 0xab, 0xf0, 0x0a, 0x8d, 0x8e, 0xa1, 0x33, 0x88,
	0xb9, 0x8c, 0x86, 0x44, 0x52, 0xdf, 0xd5, 0x66, 0xf5, 0x03, 0x5f, 0xc3, 0xae, 0x05, 0x13, 0x19,
	0x4b, 0x05, 0x45, 0x5d, 0xf0, 0x26, 0x92, 0x48, 0x25, 0x34, 0x97, 0x1b, 0x16, 0x4a, 0x53, 0x71,
	0xce, 0x78, 0x49, 0x95, 0x0b, 0xdc, 0x37, 0x8b, 0x8d, 0x52, 0xbb, 0x58, 0x09, 0xef, 0xfc, 0x07,
	0xdf, 0x5c, 0x87, 0xc7, 0x53, 0x83, 0x90, 0x3f, 0xb1, 0x09, 0x42, 0xfe, 0x77, 0xca, 0xde, 0x68,
	0x5a, 0xb4, 0x62, 0x04, 0x3e, 0x85, 0xbd, 0x7b, 0x92, 0xc4, 0x0b, 0x22, 0xe9, 0x0a, 0x9a, 0x19,
	0x74, 0x56, 0x07, 0x1f, 0x60, 0xbf, 0x1a, 0xdc, 0x08, 0xa0, 0x0b, 0xde, 0x4c, 0x50, 0x3e, 0x1a,
	0x6a, 0x82, 0x56, 0x58, 0xa8, 0x8b, 0x6f, 0x07, 0xb6, 0xfb, 0x4a, 0x46, 0x13, 0x73, 0x15, 0xe8,
	0x0a, 0x3c, 0xd3, 0x35, 0x3a, 0xec, 0xd9, 0xd3, 0xe8, 0xad, 0x9d, 0x45, 0xe0, 0xff, 0x36, 0x0c,
	0x12, 0x6e, 0xd8, 0xf8, 0x28, 0xad, 0xc7, 0xcb, 0xf2, 0xeb, 0xf1, 0xaa, 0x52, 0xdc, 0x40, 0x7d,
	0x68, 0xdb, 0x3d, 0xd1, 0x51, 0x35, 0x57, 0x2b, 0x29, 0x08, 0xfe, 0xb2, 0xcc, 0x23, 0x03, 0xf7,
	0xb1, 0x75, 0x9e, 0xcd, 0xe7, 0x9e, 0x9e, 0xb8, 0xfc, 0x09, 0x00, 0x00, 0xff, 0xff, 0x45, 0x15,
	0x0d, 0xff, 0xf4, 0x02, 0x00, 0x00,
}
